import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CrazyChess',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page-body">
          <header>
            <Link href={'/'}>CrazyChess</Link>
          </header>

          <div className="page-container">
            <aside>
              <nav>
                <Link href={'/'} >Home</Link>
                <Link href={'/game/2d'} >2D</Link>
                <Link href={'/game/3d'} >3D</Link>
              </nav>
            </aside>

            <main>
              {children}
            </main>
          </div>

          <footer>
            Footer
          </footer>
        </div>
      </body>
    </html>
  )
}
